const PREREQUISITES_MAP = {
  'Estructura de Datos': ['Fundamentos de Programacion'],
  'Programacion Orientada a Objetos I': ['Fundamentos de Programacion'],
  'Algebra Lineal': ['Matematica I'],
  'Matematica II': ['Matematica I'],
  'Analisis y Diseño de Algoritmos': ['Estructura de Datos'],
  'Programacion Orientada a Objetos II': ['Programacion Orientada a Objetos I'],
  'Matematica III': ['Matematica II'],
  'Matematicas Discretas II': ['Matematicas Discretas I'],
  'Probabilidades': ['Algebra Lineal', 'Matematica II'],
  'Algoritmos Paralelos': ['Analisis y Diseño de Algoritmos'],
  'Sistemas Distribuidos': ['Algoritmos Paralelos'],
  'Analisis y Diseño de Sistemas II': ['Analisis y Diseño de Sistemas I'],
  'Base de Datos II': ['Base de Datos I'],
  'Metodos Numericos': ['Matematica IV'],
  'Sistemas Digitales': ['Circuitos Electricos y Electronicos'],
  'Investigacion Operativa II': ['Investigacion Operativa I'],
  'Ingenieria de Software': ['Analisis y Diseño de Sistemas II', 'Base de Datos II'],
  'Business Intelligence': ['Base de Datos II'],
  'Aplicaciones Web II': ['Aplicaciones Web I'],
  'Arquitectura de Computadoras': ['Sistemas Digitales'],
  'Calidad de Software': ['Ingenieria de Software'],
  'Programacion de Dispositivos Moviles II': ['Programacion de Dispositivos Moviles I'],
  'Lenguaje de Bajo Nivel': ['Arquitectura de Computadoras'],
  'Cloud Computing': ['Data Mining'],
  'Programacion de Video Juegos II': ['Programacion de Video Juegos I'],
  'Redes II': ['Redes I'],
  'Inteligencia Artificial I': ['Procesamiento de Imagenes y Videos'],
  'Proyecto de Investigacion II': ['Proyecto de Investigacion I'],
  'Robotica II': ['Robotica I'],
  'Inteligencia Artificial II': ['Inteligencia Artificial I'],
  'Auditoria de Sistemas de Informacion': ['Seguridad Informatica'],
  'Seguridad de la Informacion': ['Seguridad Informatica'],
  'Seminario de Tesis': ['Proyecto de Investigacion II'],
  'Gestion de Proyectos II': ['Gestion de Proyectos I'],
  'Trabajo de Investigación': ['Proyecto de Investigacion II']
};

module.exports = PREREQUISITES_MAP;
